name: Publish to PyPI

on:
  release:
    types: [published]  # Runs on a release being published
  workflow_dispatch:    # Allows manual triggering

permissions:
  id-token: write       # Required for OpenID Connect (OIDC)
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI using OIDC
        uses: pypa/gh-action-pypi-publish@release/v1